//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupportDesk
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agent
    {
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public string Address { get; set; }
        public string GovernmentID { get; set; }
        public string JoinDate { get; set; }
        public string MobileNumber { get; set; }
        public string SecondaryMobileNumber { get; set; }
        public string LandlineNumber { get; set; }
        public string Email { get; set; }
        public int AgentId { get; set; }
        public string Password { get; set; }
    }
}
