//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupportDesk
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public string RoleName { get; set; }
        public Nullable<int> RoleOnwerID { get; set; }
        public string RoleDescription { get; set; }
        public int RoleID { get; set; }
    }
}
