//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupportDesk
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SupportDeskDBContext : DbContext
    {
        public SupportDeskDBContext()
            : base("name=SupportDeskDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Agent> Agents { get; set; }
        public virtual DbSet<Application> Applications { get; set; }
        public virtual DbSet<Assignee> Assignees { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Exception> Exceptions { get; set; }
        public virtual DbSet<Feature> Features { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Ticket> Tickets { get; set; }
        public virtual DbSet<TicketComment> TicketComments { get; set; }
        public virtual DbSet<TicketsDUMP> TicketsDUMPs { get; set; }
        public virtual DbSet<UserType> UserTypes { get; set; }
    }
}
