//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupportDesk
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public string TicketTitle { get; set; }
        public int StatusID { get; set; }
        public string Assignee { get; set; }
        public int AssigneeID { get; set; }
        public string SubmitDateTime { get; set; }
        public string UserQuery { get; set; }
        public Nullable<int> FeatureID { get; set; }
        public string UserFullName { get; set; }
        public int CustomerID { get; set; }
        public string Email { get; set; }
        public int ApplicationID { get; set; }
        public int IncidentID { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual Assignee Assignee1 { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Feature Feature { get; set; }
        public virtual Status Status { get; set; }
    }
}
