//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupportDesk
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketsDUMP
    {
        public string IncidentId { get; set; }
        public string TicketTitle { get; set; }
        public string Status { get; set; }
        public string Assignee { get; set; }
        public string SubmitDateTime { get; set; }
        public string Date { get; set; }
        public string FiscalMonth { get; set; }
        public string UserQuery { get; set; }
        public string WhatAskGMMFeatureDoesYourQuestionPertainTo_ { get; set; }
        public string UserFullName { get; set; }
        public string Email { get; set; }
        public string ApplicationName { get; set; }
        public string LastModifiedDate { get; set; }
    }
}
